name: CI Pipeline

on: 
  push:
    branches: [main]   #only runs on main branch , nothing happens when pushing to feature branch

jobs: 
  build:
    runs-on: ubuntu-latest

  steps:        # actual instructions to be executed
    - name: Checkout code
      uses: actions/checkout@v5           # https://github.com/actions/checkout

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    # - name:
    #   uses:
    #   run:
      
